### ISSUE TITLE
IntelliSense issues VS2015 RTM with Beta7 DNXes

### ISSUE THREAD

**Issue by anurse** [aspnet/Announcements#44]
Visual Studio 2015 RTM shipped with code to handle a new set of names for DNX runtime assemblies. Unfortunately, these renames have not yet landed in the aspnetvnext feed, so the Visual Studio experience is broken when working with the latest DNX builds from aspnetvnext.

A fix is coming soon in the form of an updated version of the ASP.NET Visual Studio tools, but in the interim, you can set the `WEBPROJ_ENABLEBETA7RENAMES` environment variable to `0` to disable the use of the renamed assemblies. We recommend setting this value in your User-level environment variables until you can install the updated version of the tooling.

If you are seeing IntelliSense issues with DNX projects, this may fix the problem.

**If you are working with Beta6 (or lower) packages and DNX, NO ACTION IS REQUIRED**

**Comment by anurse** [comment]
If you see output such as the following in your Visual Studio Output Window, you are hitting this issue and should try this workaround:

```
Could not load file or assembly 'Microsoft.DNX.PackageManager' or one of its dependencies. The system cannot find the file specified
```

You may also see

```
Could not load file or assembly 'Microsoft.DNX.DesignTimeHost' or one of its dependencies. The system cannot find the file specified
```

**Comment by TheMadKow** [comment]
I'm not sure if it is related, but i'm getting "Image is too small" exception when building, on Microsoft.DNX.Targets under 

<DesignTimeHostBuild
      Condition="'$(_DesignTimeHostBuild)' == 'true'"
      Port="$(DTHPort)"
      HostID="$(DTHHostID)"
      ContextID="$(DTHContextID)"
      DTHProtocolVersion="$(DTHProtocolVersion)"
      Rebuild ="$(RebuildInvoked)"
    />

**Comment by anurse** [comment]
As far as I know that would be unrelated. You could file it on https://github.com/aspnet/Tooling to get it in front of the right eyes. The more information you can post there, the better (project.json content, version of DNX in use, etc.).

Hope that helps!

**Comment by GuardRex** [comment]
> A fix is coming soon

@DamianEdwards said on the [Community Standup](https://www.youtube.com/watch?feature=player_embedded&v=7O81CAjmOXk#t=1234) that this fix would be out in a week or so. Do we get the fix via `Tools > Extensions and Updates ...`? ... and when that fix is available, you'll report it here?

**Comment by anurse** [comment]
It should appear in that list. The update will be available when Beta6 releases.

**Comment by ardalis** [comment]
@anurse is a reboot required after setting the env var? I set it and restarted VS but still get the same error when building. I'm trying to use Beta5 but it's attempting to use beta7, too, so that may be related. Can I adjust that in VS or do I need to do that from the console?

A bit of the relevant output:
C:\Users\Steve\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12264\bin\dnx.exe --appbase "C:\dev\github\aspnet-logging\src\Microsoft.Framework.Logging.Abstractions" "C:\Users\Steve\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12264\bin\lib\Microsoft.DNX.PackageManager\Microsoft.DNX.PackageManager.dll" pack "C:\dev\github\aspnet-logging\src\Microsoft.Framework.Logging.Abstractions" --configuration Debug --out "..\..\artifacts\bin\Microsoft.Framework.Logging.Abstractions"
6>  C:\Users\Steve\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12264\bin\dnx.exe --appbase "C:\dev\github\aspnet-logging\src\Microsoft.Framework.Logging.Console" "C:\Users\Steve\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12264\bin\lib\Microsoft.DNX.PackageManager\Microsoft.DNX.PackageManager.dll" pack "C:\dev\github\aspnet-logging\src\Microsoft.Framework.Logging.Console" --configuration Debug --out "..\..\artifacts\bin\Microsoft.Framework.Logging.Console"
3>  System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DNX.PackageManager' or one of its dependencies. The system cannot find the file specified.
3>  File name: 'Microsoft.DNX.PackageManager'

**Comment by anurse** [comment]
No, a reboot shouldn't be required. You would need to relaunch VS and any command prompt windows (if you use those to launch VS) if you set it in the Machine/User environment variables.

VS will use whatever your dnvm default alias is, or the value you set in the global.json sdk.version property.

**Comment by sergeyzwezdin** [comment]
@anurse @ardalis did you resolved this problem guys? I added `WEBPROJ_ENABLEBETA7RENAMES` variable but also still getting the error.

**Comment by anfomin** [comment]
@sergeyzwezdin with **dnx-beta7-12290+** you should remove this variable and install new tools from [this post](https://github.com/aspnet/Announcements/issues/51).

**Comment by anurse** [comment]
Thanks @anfomin ! I've updated the issue to indicate this. I suppose we could close this issue now since it is no longer relevant to the latest beta7 builds, but I'm not sure what our process is for that (/cc @Eilon @danroth27)

**Comment by Eilon** [comment]
Can leave this issue open because people might be using those bits - however, I'd edit the original issue to clarify exactly what it applies to.

**Comment by sergeyzwezdin** [comment]
@anfomin @anurse Thank you!

**Comment by realavaloro** [comment]
What if the problem happens when building in Azure with Visual Studio Build??
How do we fix the ```Could not load file or assembly 'Microsoft.DNX.PackageManager' or one of its dependencies``` issue when using dnx-clr-win-x86.1.0.0-beta7

**Comment by anurse** [comment]
It should work as long as Visual Studio Build has the latest ASP.NET tools installed.

As per the comments in https://github.com/aspnet/Announcements/issues/47#issuecomment-125018011, I'm locking this thread to avoid spamming people watching this repo too much. @realavaloro Please feel free to use the discussion thread at https://github.com/aspnet/dnx/issues/2678 to continue discussing if you are still having problems.
